name: Build React Native Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository and any submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 2. Sets up the Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or the version specified in your project
          cache: 'npm'

      # 3. Installs the JavaScript dependencies from the root directory
      - name: Install JavaScript dependencies
        run: npm install

      # 4. Sets up the Java Development Kit (JDK) for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 5. Grants execute permission to the gradlew script
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./android

      # 6. Builds the Android App (usually assembleRelease)
      - name: Build Android Release
        run: ./gradlew assembleRelease
        working-directory: ./android
