jobs:
  build:
    runs-on: ubuntu-latest

    # Add this line to set a default directory for all steps in this job
    defaults:
      run:
        working-directory: ./your-project-folder-name  # 💡 CHANGE THIS

    steps:
      # 1. Downloads your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the Java environment needed for Android
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. Gives permission to the Gradle build tool
      # This step will now run inside your project folder
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Runs the command to build a debug APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. Saves the generated APK as a downloadable file
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # Update the path to include the subdirectory
          path: your-project-folder-name/app/build/outputs/apk/debug/app-debug.apk # 💡 CHANGE THIS
